"""Assemble the manuscript from the computed results.

Every numeric claim is read from tables/NUMBERS.json, which is generated by
scripts/collect_numbers.py directly from the result CSVs. Nothing is typed by
hand, so a number in the text cannot drift from the analysis that produced it.
"""
import json, os, datetime
import pandas as pd
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

N = json.load(open("tables/NUMBERS.json"))
RA = pd.read_csv("results/reference_audit.csv")
doc = Document()

# ------------------------------------------------------------------ styling
st = doc.styles["Normal"]
st.font.name = "Calibri"; st.font.size = Pt(10.5)
st.paragraph_format.space_after = Pt(6)
st.paragraph_format.line_spacing = 1.15
for lvl, sz in [("Title", 18), ("Heading 1", 13), ("Heading 2", 11.5), ("Heading 3", 10.5)]:
    s = doc.styles[lvl]
    s.font.name = "Calibri"; s.font.size = Pt(sz); s.font.color.rgb = RGBColor(0x1c, 0x24, 0x30)
    s.font.bold = True


def P(text="", style=None, italic=False, size=None, align=None, space=None):
    p = doc.add_paragraph(style=style)
    r = p.add_run(text)
    r.italic = italic
    if size:
        r.font.size = Pt(size)
    if align == "c":
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if space is not None:
        p.paragraph_format.space_after = Pt(space)
    return p


def RICH(parts, size=None, space=None):
    """parts: list of (text, style) where style in {'', 'i', 'b'}."""
    p = doc.add_paragraph()
    for t, s in parts:
        r = p.add_run(t)
        r.italic = "i" in s
        r.bold = "b" in s
        if size:
            r.font.size = Pt(size)
    if space is not None:
        p.paragraph_format.space_after = Pt(space)
    return p


def H(text, lvl=1):
    doc.add_heading(text, level=lvl)


def FIG(path, caption_bold, caption, width=6.4):
    if os.path.exists(path):
        doc.add_picture(path, width=Inches(width))
        doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    p = doc.add_paragraph()
    r = p.add_run(caption_bold); r.bold = True; r.font.size = Pt(9)
    r2 = p.add_run(" " + caption); r2.font.size = Pt(9)
    p.paragraph_format.space_after = Pt(12)


def TABLE(df, caption_bold, caption, widths=None, fontsize=8.5):
    p = doc.add_paragraph()
    r = p.add_run(caption_bold); r.bold = True; r.font.size = Pt(9)
    r2 = p.add_run(" " + caption); r2.font.size = Pt(9)
    t = doc.add_table(rows=1, cols=len(df.columns))
    t.style = "Light Grid Accent 1"
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    for j, c in enumerate(df.columns):
        cell = t.rows[0].cells[j]
        cell.text = ""
        run = cell.paragraphs[0].add_run(str(c))
        run.bold = True; run.font.size = Pt(fontsize)
    for _, row in df.iterrows():
        cells = t.add_row().cells
        for j, v in enumerate(row):
            cells[j].text = ""
            run = cells[j].paragraphs[0].add_run("" if pd.isna(v) else str(v))
            run.font.size = Pt(fontsize)
    if widths:
        for j, w in enumerate(widths):
            for rrow in t.rows:
                rrow.cells[j].width = Inches(w)
    doc.add_paragraph().paragraph_format.space_after = Pt(6)


def ref(key, field):
    row = RA[RA.key == key]
    if not len(row):
        return ""
    return row.iloc[0][field]


def cite(key):
    a = ref(key, "first_author"); y = ref(key, "year")
    try:
        y = int(float(y))
    except Exception:
        pass
    return f"{a} et al., {y}"


exec(open("scripts/manuscript_body.py", encoding="utf-8").read())

out = "CNCM_I745_DigitalTwin_v4.docx"
doc.save(out)
print("wrote", out, os.path.getsize(out), "bytes;", len(doc.paragraphs), "paragraphs")
