# -*- coding: utf-8 -*-
# Executed inside build_manuscript.py, which supplies P, RICH, H, FIG, TABLE,
# N (tables/NUMBERS.json), RA (reference audit) and cite().
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

f = lambda x, n=3: f"{x:.{n}f}"
i = lambda x: f"{int(x):,}"
pct = lambda x, n=0: f"{100*x:.{n}f}%"

# ====================================================================== TITLE
P("A mechanistic digital twin of Saccharomyces cerevisiae var. boulardii "
  "CNCM I-745: strain-specific metabolism, gastric bioenergetics, and "
  "dose-dependent exclusion of Clostridioides difficile", style="Title")
P("", space=2)
P("Reproducible computational study. All numeric values in this manuscript are "
  "generated by the analysis pipeline and injected at build time; none are "
  "transcribed by hand.", italic=True, size=9)
P(f"Build date: {__import__('datetime').date.today().isoformat()}", size=9, italic=True)

# =================================================================== ABSTRACT
H("Abstract", 1)
RICH([
 ("Background. ", "b"),
 ("Saccharomyces cerevisiae", "i"),
 (" var. ", ""), ("boulardii", "i"),
 (" CNCM I-745 is the only yeast in routine clinical probiotic use, yet "
  "quantitative models of its behaviour in the gastrointestinal tract remain "
  "scarce. Existing strain-specific reconstructions assert gene losses from "
  "the literature and assume that removing those genes produces a "
  "functionally distinct model. We tested that assumption directly.", "")])
RICH([
 ("Methods. ", "b"),
 (f"We screened {N['l1_n_query_genes']} reference proteins by translated "
  f"alignment against {N['l1_n_assemblies_screened']} genome assemblies, "
  "resolving paralogues at locus level. Genes with no intact homologue in any "
  "qualifying assembly were removed from the Yeast9 consensus model by "
  "abstract-syntax-tree editing of the gene-protein-reaction rules, "
  "distinguishing rule rewriting from reaction deletion. The corrected model "
  "was evaluated by flux balance analysis across carbon and nitrogen sources, "
  "by a complete single-gene deletion screen, and under expression "
  "constraints derived from genome-wide microarray data for three intestinal "
  "zones. Gastric transit was modelled bioenergetically as the ATP cost of "
  "maintaining the transmembrane proton gradient. Toxin A proteolysis was "
  "calibrated by Markov chain Monte Carlo against published measurements, and "
  "colonisation resistance was modelled as two-species resource competition "
  "in a continuously dosed flow compartment.", "")])
RICH([
 ("Results. ", "b"),
 (f"{N['l1_khatri_confirmed']} of {N['l1_khatri_testable']} previously "
  f"reported gene absences replicated in all {N['l1_n_boulardii_qualifying']} "
  "qualifying assemblies; one public deposit failed strain-level quality "
  f"control (core-gene identity {f(N['l1_kctc_core_pid_min'],1)}–"
  f"{f(N['l1_kctc_core_pid_max'],1)}%) and was excluded. The galactose "
  "pathway is intact in every assembly despite the documented "
  "galactose-negative phenotype. Gene-content correction produced "
  f"{N['l2_n_gpr_edits']} rule edits and {N['l2_n_deleted']} reaction "
  f"deletions but changed essentiality in {N['l2_ess_n_changed']} genes and "
  f"growth on {N['l2_n_substrates'] - N['l2_n_differing']} of "
  f"{N['l2_n_substrates']} substrates not at all; the single differential "
  "phenotype is loss of trehalose utilisation. Paralogue loss becomes "
  "quantitatively relevant only when transport capacity is limiting, where it "
  f"imposes up to a {f(N['l2_capacity']['galactose']['max_deficit_pct'],0)}% "
  "growth deficit on galactose against "
  f"{f(N['l2_capacity']['glucose']['max_deficit_pct'],0)}% on glucose. At pH "
  f"2 the proton pump costs {f(N['l3_pump_cost_pH2'],0)} kJ per mole of H+, "
  "and survival requires a plasma-membrane proton leak below "
  f"{N['l3_kleak_lethal_at_pH2']} L gDW-1 h-1. Toxin A half-life is "
  f"{f(N['l4_posterior']['half_life_h']['median'],2)} h "
  f"({f(N['l4_posterior']['half_life_h']['lo95'],2)}–"
  f"{f(N['l4_posterior']['half_life_h']['hi95'],2)}, 95% credible interval). "
  "In the competition model, exclusion of ", ""),
 ("C. difficile", "i"),
 (" requires continuous dosing: a single inoculum washes out, and the "
  f"minimum effective dose is {N['l6_min_dose_overall']} g dry biomass per "
  "day at physiological transit rates, rising at both slower and faster "
  "transit.", "")])
RICH([
 ("Conclusions. ", "b"),
 ("Strain-specific gene content is, by itself, almost metabolically silent in "
  "this organism. The behaviours that matter clinically are set by transport "
  "capacity, bioenergetics under acid stress, and ecological competition "
  "under continuous dosing, none of which are captured by gene deletion. We "
  "state the resulting predictions in falsifiable form and provide the model, "
  "data provenance and an interactive interface.", "")])

# =============================================================== INTRODUCTION
H("1. Introduction", 1)
RICH([
 ("Saccharomyces cerevisiae", "i"), (" var. ", ""), ("boulardii", "i"),
 (" CNCM I-745 is used clinically for antibiotic-associated diarrhoea and as "
  "adjunctive therapy in ", ""), ("Clostridioides difficile", "i"),
 (f" infection ({cite('mcfarland2010')}; {cite('czerucka2007')}). Its "
  "mechanisms are usually described qualitatively: proteolysis of toxin A, "
  "modulation of inflammatory signalling, competition for nutrients, and "
  "trophic effects on the epithelium. Quantitative, mechanistic models that "
  "connect these to genome content are rare, and the ones that exist inherit "
  "a structural weakness — they assume that a strain-specific metabolic model "
  "follows from deleting the genes the strain has lost.", "")])
RICH([
 ("That assumption deserves testing rather than assertion, for two reasons. "
  "First, the gene losses themselves are usually taken from the literature "
  "rather than verified against the assembly being modelled; a single "
  "mis-specified accession propagates silently into every downstream number. "
  "Second, most of the reported losses in this organism are members of "
  "paralogous families, and removing one member of a redundant family changes "
  "a model's gene annotation without changing its flux space. A reconstruction "
  "can therefore look strain-specific while being metabolically identical to "
  "its parent.", "")])
RICH([
 ("We rebuilt the model from the genome up, testing each step rather than "
  "carrying it forward. Where the gene-content approach fails — and we show "
  "that it largely does — we replace it with mechanisms that are actually "
  "capable of explaining the observed physiology: transport capacity limits, "
  "the bioenergetic cost of acid tolerance, and resource competition under "
  "continuous dosing. Each is expressed as a quantitative prediction with a "
  "stated experiment that would refute it.", "")])

# ======================================================================= DATA
H("2. Methods", 1)
H("2.1 Data and provenance", 2)
RICH([
 (f"All inputs were downloaded programmatically and recorded in a provenance "
  f"ledger ({N['provenance_entries']} entries) carrying the source URL, "
  "accession or release tag, byte size, SHA-256 digest and retrieval "
  f"timestamp. Genome assemblies were obtained from NCBI Datasets "
  f"({cite('sayers2022')}); the metabolic reconstruction is the Yeast9 "
  f"consensus model ({cite('yeast9')}) at a pinned release; expression data "
  f"are the environmental stress response series GSE18 ({cite('gasch2000')}) "
  f"retrieved from GEO ({cite('barrett2013')}).", "")])

H("2.2 Layer 1 — evidence-based comparative genomics", 2)
RICH([
 (f"We assembled a query panel of {N['l1_n_query_genes']} ", ""),
 ("S. cerevisiae", "i"),
 (" S288C proteins comprising every gene reported absent from ", ""),
 ("S. boulardii", "i"),
 (", the paralogues that compete with those genes for alignment hits, the "
  "galactose regulon, and eight constitutively expressed core genes as "
  "controls. Each protein was searched against every assembly with tblastn "
  f"({cite('camacho2009')}). High-scoring pairs were merged into loci by "
  "genomic coordinate, and competition between paralogous queries at "
  "overlapping loci was resolved by summed bitscore with a reciprocal-overlap "
  "criterion; loci whose two best queries score within 2% of one another are "
  "reported as paralogue-ambiguous rather than assigned. A gene is called "
  "present when it wins at least one locus at ≥90% identity and ≥80% query "
  "coverage. The core-gene panel serves two purposes: it establishes method "
  "sensitivity on the reference genome, and it detects deposits that are not "
  "the organism they claim to be.", "")])
RICH([
 ("Introgression was tested independently by searching a ", ""),
 ("Zygosaccharomyces bailii", "i"),
 (" proteome against two ", ""), ("S. boulardii", "i"),
 (" assemblies and against S288C, retaining proteins with high identity in "
  "the former and none in the latter.", "")])

H("2.3 Layer 2 — strain-specific genome-scale model", 2)
RICH([
 ("Genes absent from every qualifying assembly were removed from Yeast9 by "
  "parsing each gene-protein-reaction rule to an abstract syntax tree and "
  "deleting only the affected literals. A reaction is disabled only when its "
  "rule evaluates to empty. We report rule rewriting and reaction deletion "
  "separately throughout, because conflating them is the error that makes a "
  "corrected model appear more strain-specific than it is. Flux balance and "
  f"parsimonious flux balance analysis ({cite('orth2010')}) were performed "
  f"with COBRApy ({cite('ebrahim2013')}) under gut-like exchange constraints, "
  "and the complete single-gene deletion screen was run on both models under "
  "identical media.", "")])
RICH([
 ("Because rescaling an already non-binding bound changes nothing, transport "
  "capacity was expressed in absolute units: each retained paralogue of a "
  "multi-paralogue transport reaction contributes a fixed catalytic capacity, "
  "and that single parameter was swept over two orders of magnitude. This "
  "converts a qualitative statement about gene loss into a quantitative one "
  "about the regime in which it matters.", "")])

H("2.4 Layer 3 — zone metabolism and gastric bioenergetics", 2)
RICH([
 (f"Expression constraints were applied by E-Flux ({cite('colijn2009')}), "
  "using the canonical formulation and, for comparison only, the square-root "
  "geometric-mean variant used in earlier drafts of this work. Rather than a "
  "point estimate per zone, each zone was evaluated over an ensemble of "
  "expression draws resampled within the between-array standard deviation, so "
  "every reported flux carries an interval reflecting measurement "
  "uncertainty. Zone contrasts were tested per reaction by Welch's t-test "
  "with Benjamini–Hochberg control of the false discovery rate "
  f"({cite('benjamini1995')}).", "")])
RICH([
 ("No acid-shock condition exists in the expression series, so the gastric "
  "zone is not proxied by an unrelated stress. It is modelled instead from "
  "first principles. The plasma-membrane H+-ATPase exports one proton per ATP "
  "hydrolysed; the free energy required to move a mole of protons from the "
  "cytosol to the lumen against the membrane potential sets a minimum ATP "
  "cost, and passive re-entry of protons at a rate proportional to the "
  "luminal concentration sets the flux that must be pumped. The product is an "
  "additional non-growth-associated maintenance demand, imposed on the model "
  "as a pH-dependent constraint. Cytosolic pH is bounded by the "
  "thermodynamic ceiling of a one-proton-per-ATP pump rather than held "
  f"constant ({cite('orij2012')}).", "")])

H("2.5 Layer 4 — host interaction kinetics", 2)
RICH([
 ("Two provenance corrections were required. The activity that cleaves ", ""),
 ("C. difficile", "i"),
 (f" toxin A is a 54 kDa serine protease ({cite('castagliuolo1996')}; "
  f"{cite('castagliuolo1999')}); it is not CAMP factor, which is an unrelated "
  "haemolysin co-factor of other genera. The alkaline phosphatase described "
  f"by {cite('buts2006')} dephosphorylates lipopolysaccharide endotoxin and "
  "does not act on toxin A; it is modelled here as a separate activity.", "")])
RICH([
 ("Rather than fixing rate constants, the proteolysis model was calibrated by "
  f"affine-invariant MCMC ({cite('foremanmackey2013')}) against two "
  "quantities reported in the source experiments: the fraction of toxin "
  "activity lost after one hour of protease exposure, and the share of total "
  "clearance that is protease-dependent. Including spontaneous decay as a "
  "third parameter makes those two observations separately informative. "
  "Reported quantities are posterior medians with 95% credible intervals.", "")])
RICH([
 ("The NF-κB and cytokine module is deliberately not fitted: no citable "
  "quantitative time course exists to fit it to, and presenting tuned "
  "parameters as calibrated ones would be misleading. It is analysed instead "
  f"by Sobol variance decomposition ({cite('herman2017')}), which identifies "
  "which parameters would have to be measured for its predictions to become "
  "meaningful, and reported as a prior-predictive interval.", "")])

H("2.6 Layer 5 — surrogate model", 2)
RICH([
 ("A Latin hypercube design over four exchange bounds was labelled by flux "
  "balance analysis and used to train a surrogate. Two departures from the "
  "earlier design are deliberate. The surrogate is a multilayer perceptron "
  "rather than a one-dimensional convolutional network: convolution assumes "
  "locality along the input axis, and the input here is four unordered "
  "nutrient bounds for which no such ordering exists. Predictive uncertainty "
  "comes from a five-member deep ensemble rather than Monte-Carlo dropout, "
  "and its calibration is checked against held-out coverage. Ridge "
  "regression, random forests and gradient boosting were trained on identical "
  f"folds ({cite('pedregosa2011')}), because a surrogate is only worth having "
  "if it beats the cheap alternatives. Inference speed was measured against "
  "the linear program rather than asserted.", "")])

H("2.7 Layer 6 — competition and colonisation resistance", 2)
RICH([
 ("The yeast and ", ""), ("C. difficile", "i"),
 (" compete for a single limiting carbohydrate in a continuous-flow "
  "compartment whose dilution rate represents intestinal transit. The yeast "
  "inhibits ", ""), ("C. difficile", "i"),
 (" growth in proportion to its own biomass, and clears secreted toxin A "
  "through the protease of Layer 4. Critically, the yeast enters in the feed "
  "rather than only as an initial inoculum: ", ""),
 ("S. boulardii", "i"),
 (" is not a coloniser, so a model without a dosing term can only predict "
  "washout. Daily dose is converted to a feed concentration through the "
  "dilution rate and a one-litre luminal compartment.", "")])

# ==================================================================== RESULTS
H("3. Results", 1)

H("3.1 The reference genome was modelled in place of the strain", 2)
RICH([
 (f"The assembly statistics we compute for the ", ""),
 ("S. cerevisiae", "i"),
 (f" S288C reference — {i(N['l1_s288c_seqs'])} sequences, "
  f"{i(N['l1_s288c_bp'])} bp, N50 {i(N['l1_s288c_n50'])} bp, "
  f"{f(N['l1_s288c_gc'],2)}% GC — are those reported in earlier versions of "
  "this work as characterising CNCM I-745. Genuine ", "")  ,
 ("S. boulardii", "i"),
 (f" assemblies span {i(N['l1_sb_bp_min'])}–{i(N['l1_sb_bp_max'])} bp with "
  f"{f(N['l1_sb_gc_min'],2)}–{f(N['l1_sb_gc_max'],2)}% GC. The genome "
  "previously analysed therefore contained the very transporter genes whose "
  "absence was being reported. Section 5 records the resulting corrections in "
  "full.", "")])

H("3.2 Reported gene losses replicate, with exceptions that matter", 2)
RICH([
 (f"Across {N['l1_n_boulardii_qualifying']} qualifying assemblies, "
  f"{N['l1_khatri_confirmed']} of {N['l1_khatri_testable']} testable reported "
  "absences were confirmed with no intact homologue anywhere "
  f"(Figure 1). Method sensitivity is {N['l1_control_recovery']} of "
  f"{N['l1_control_total']} on the reference control, so these are not false "
  "negatives. The unconfirmed cases (", ""),
 (", ".join(N["l1_khatri_unconfirmed"]), "i"),
 (") belong to multigene families whose members are not separable by "
  "alignment, and we report them as undetermined rather than present.", "")])
RICH([
 ("Two corrections to the gene list follow. The maltose losses are confined "
  "to the MAL1 locus; the MAL3 locus is intact, so the loss is partial rather "
  "than complete. The isomaltase losses are IMA2, IMA3 and IMA4, with IMA1 "
  "and IMA5 retained.", "")])
RICH([
 ("One public deposit is not the organism it claims to be. Its core "
  f"housekeeping proteins have a median identity of "
  f"{f(N['l1_kctc_core_pid_median'],1)}% to their ", ""),
 ("S. cerevisiae", "i"),
 (f" orthologues, with {N['l1_kctc_core_below95']} of "
  f"{N['l1_n_core_controls']} below 95%, against a median of "
  f"{f(N['l1_sb_core_pid_median'],1)}% and "
  f"{N['l1_sb_core_below95']} below 95% across all other assemblies "
  "combined — divergence at the level of a different species, not a "
  "different strain. We excluded it and flag it for anyone using that "
  "accession.", "")])
RICH([
 ("The ", ""), ("Z. bailii", "i"),
 (f" introgression was recovered independently: {N['l1_introgressed_genes']} "
  f"proteins at {f(N['l1_introgression_pid_min'],1)}–"
  f"{f(N['l1_introgression_pid_max'],1)}% identity, each present in "
  f"{N['l1_introgression_copies']} copies in tandem on chromosome IV, with no "
  f"counterpart above {f(N['l1_introgression_sc_pid_max'],0)}% identity in "
  "S288C.", "")])

FIG("figures/figure1_genomics.png", "Figure 1.",
    "Evidence-based comparative genomics. (a) Presence calls for the query "
    "panel across all assemblies; the reference genome is the leftmost column "
    "and the disqualified deposit the rightmost. (b) Core-gene identity "
    "distinguishes strain-level variation from a misidentified deposit. "
    "(c) Concordance with previously reported absences; bars show the number "
    "of qualifying assemblies with no intact copy.")

H("3.3 The galactose-negative phenotype is not explained by gene loss", 2)
RICH([
 ("Every structural and regulatory gene of the galactose pathway (", ""),
 (", ".join(N["l1_gal_genes"]), "i"),
 (") is intact in all qualifying assemblies. ", "")  ,
 ("S. boulardii", "i"),
 (" is nevertheless documented as galactose-negative. No gene-content-based "
  "correction can reproduce that phenotype, which places a hard limit on what "
  "the strain-specific-GEM approach can deliver for this organism: the defect "
  "must be regulatory or allelic rather than a deletion. We treat this as a "
  "finding rather than a modelling failure, and it motivates the capacity and "
  "bioenergetic layers that follow.", "")])

H("3.4 Gene-content correction is almost metabolically silent", 2)
RICH([
 (f"Of {N['l1_n_absent_all6']} genes absent from every assembly, "
  f"{N['l2_n_absent_in_model']} carry a gene-protein-reaction association in "
  f"Yeast9, and {N['l2_n_gpr_edits']} reactions required a rule edit. Only "
  f"{N['l2_n_deleted']} reactions lose their sole catalyst; the remaining "
  f"{N['l2_n_rewritten_only']} retain isoenzymes and are unchanged in flux "
  "space (Figure 2a). The consequences are smaller than the edit count "
  "suggests.", "")])
RICH([
 (f"The complete single-gene deletion screen classifies "
  f"{N['l2_ess_base'].get('essential', 0)} genes as essential in the parent "
  f"model and {N['l2_ess_strain'].get('essential', 0)} in the corrected "
  f"model, with {N['l2_ess_n_changed']} genes changing category — no gains "
  "and no losses (Figure 2b). Across "
  f"{N['l2_n_substrates']} carbon and nitrogen sources, growth differs on "
  f"{N['l2_n_differing']}: ", ""),
 (", ".join(N["l2_differing"]), "i"),
 (" (Figure 2c). The trehalose result is a genuine prediction — the sole "
  "trehalose transporter is lost with MAL11/AGT1 — and it is falsifiable by a "
  "single growth assay.", "")])
RICH([
 ("This is the paper's central negative result. A strain-specific metabolic "
  "model built by deleting lost genes is, for this organism, "
  "indistinguishable from its parent under almost every condition tested. "
  "Published reconstructions that report strain-specific behaviour from gene "
  "content alone should be checked against this null.", "")])

H("3.5 Scored against the phenotype panel, the two models are indistinguishable", 2)
ps = N.get("l2_phenotype_scores", {}); mcn = N.get("l2_mcnemar", {})
if ps and mcn:
    RICH([
     (f"We scored both models against a curated panel of {N['l2_panel_n']} carbon "
      f"and nitrogen sources, of which {N['l2_panel_representable']} are "
      "representable as exchange reactions and every cell of which carries its "
      "literature source and gene-level basis. Against the ", ""),
     ("S. cerevisiae", "i"),
     (f" observations the parent model is correct on "
      f"{ps['Yeast9_base']['TP'] + ps['Yeast9_base']['TN']} of "
      f"{ps['Yeast9_base']['n']}. Against the ", ""),
     ("S. boulardii", "i"),
     (f" observations the corrected model is correct on "
      f"{ps['CNCM_I745']['TP'] + ps['CNCM_I745']['TN']} of "
      f"{ps['CNCM_I745']['n']}, with {ps['CNCM_I745']['FP']} false positives — "
      "it predicts growth on galactose, palatinose and maltose, which the "
      f"organism does not do. The Matthews correlation coefficient is "
      f"{f(ps['CNCM_I745']['mcc'],2)} because the model never predicts a "
      "negative.", "")])
    RICH([
     (f"An exact McNemar test over the {mcn['n_pairs']} paired predictions finds "
      f"{mcn['discordant']} discordant pairs (p = {f(mcn['p_exact'],2)}): the "
      "corrected model neither fixes nor breaks a single call relative to its "
      "parent. This is the negative result in its sharpest form. It also shows "
      "why the panel is short — we would rather report six sourced observations "
      "with no power than twenty unsourced ones with false precision.", "")])

H("3.6 Paralogue loss matters only when transport capacity binds", 2)
RICH([
 ("Gene deletion is silent because the deleted transporters are members of "
  "large families and the model's default bounds are non-binding. Expressing "
  "capacity in absolute units per retained paralogue makes the loss visible "
  "and quantifies the regime in which it operates (Figure 2d). Galactose, "
  "which depends on the fewest remaining permeases, suffers up to a "
  f"{f(N['l2_capacity']['galactose']['deficit_at_1_pct'],0)}% growth deficit at "
  "a capacity of 1 mmol gDW-1 h-1 per permease, and fails entirely below "
  f"{N['l2_capacity']['galactose']['binding_v_lo']}; maltose loses "
  f"{f(N['l2_capacity']['maltose']['deficit_at_1_pct'],0)}%; glucose loses "
  f"{f(N['l2_capacity']['glucose']['deficit_at_1_pct'],0)}%, "
  "because the hexose transporter family is large enough to buffer the loss. "
  "Above roughly 3 mmol gDW-1 h-1 per paralogue, all differences vanish.", "")])

FIG("figures/figure2_gem.png", "Figure 2.",
    "Strain-specific genome-scale model. (a) Gene-protein-reaction edits, "
    "showing which reactions retain isoenzymes and which lose their only "
    "catalyst. (b) Essentiality classes are identical between models. "
    "(c) Growth across carbon and nitrogen sources. (d) Growth ratio as a "
    "function of assumed catalytic capacity per retained paralogue.")

H("3.7 Zone metabolism with propagated measurement uncertainty", 2)
RICH([
 (f"Genome-wide expression covers {i(N['l3_genes_per_zone'])} genes per zone "
  f"and maps onto {i(N['l3_n_gpr_mapped'])} of {i(N['l3_n_reactions_constrained'])} "
  "GPR-bearing reactions (Figure 3a) — a coverage the hand-curated "
  "fold-change tables used in earlier drafts cannot approach. The canonical "
  "and variant E-Flux formulations give indistinguishable growth rates, so "
  "the variant is not a source of discrepancy.", "")])
sigtxt = ", ".join(f"{k.replace('_', ' ')}: {v}" for k, v in sorted(N["l3_significant"].items()))
RICH([
 (f"Testing all {i(N['l3_n_tested_per_contrast'])} reactions per contrast with "
  f"FDR control gives {sigtxt} significantly different reactions "
  "(Figure 3d). We note explicitly that the duodenum–colon contrast confounds "
  "expression with the zone's oxygen availability; the largest effects there "
  "are respiratory-chain reactions, which is a consequence of the imposed "
  "oxygen bound rather than of the expression data.", "")])

H("3.8 Gastric survival is a bioenergetic problem, not a genetic one", 2)
RICH([
 (f"At luminal pH 2 the H+-ATPase must do {f(N['l3_pump_cost_pH2'],1)} kJ of "
  f"work per mole of protons exported, against {f(N['l3_pump_cost_pH7'],1)} "
  "kJ at neutral pH. The resulting maintenance demand exceeds the model's "
  f"basal requirement of {N['l3_ngam_basal']} mmol ATP gDW-1 h-1 over most of "
  "the plausible leak range (Figure 3c), and growth ceases at pH 2 once the "
  f"proton-leak coefficient reaches {N['l3_kleak_lethal_at_pH2']} L gDW-1 "
  f"h-1 (Figure 3b). Survival pH rises monotonically with leak, from "
  f"{min(N['l3_survival_pH'].values())} at the lowest leak tested to "
  f"{max(N['l3_survival_pH'].values())} at the highest.", "")])
RICH([
 ("Because gene content is identical between the two models in this respect, "
  "the prediction is unambiguous: the acid tolerance that distinguishes ", ""),
 ("S. boulardii", "i"),
 (" from laboratory ", ""), ("S. cerevisiae", "i"),
 (" must reside in membrane proton permeability or pump capacity, not in gene "
  "presence. That is directly measurable.", "")])

FIG("figures/figure3_zones.png", "Figure 3.",
    "Gut-zone metabolism and gastric bioenergetics. (a) Genome-wide "
    "expression distributions per zone. (b) Growth versus luminal pH across "
    "proton-leak coefficients. (c) The additional ATP maintenance demand "
    "imposed by acid, relative to basal maintenance. (d) Reaction-level "
    "contrast between ileum and colon with FDR control.")

H("3.9 Toxin A clearance, calibrated rather than assumed", 2)
po = N["l4_posterior"]
RICH([
 (f"The posterior gives a toxin A half-life of {f(po['half_life_h']['median'],2)} h "
  f"(95% credible interval {f(po['half_life_h']['lo95'],2)}–"
  f"{f(po['half_life_h']['hi95'],2)}) and reproduces both calibration "
  f"anchors: {pct(po['frac_1h']['median'],1)} "
  f"({pct(po['frac_1h']['lo95'],0)}–{pct(po['frac_1h']['hi95'],0)}) of toxin "
  f"degraded in one hour, and {pct(po['protease_share']['median'],1)} "
  f"({pct(po['protease_share']['lo95'],0)}–{pct(po['protease_share']['hi95'],0)}) "
  f"of clearance protease-dependent (Figure 4a,b). Vmax and Km are strongly "
  "correlated in the posterior and are not separately identified by these two "
  "observations (Figure 4c) — a limitation that a time-resolved proteolysis "
  "assay would resolve, and one that point estimates would have concealed.", "")])
st_ = N["l4_sobol_top"]; ppv = N["l4_nfkb_prior_predictive"]
RICH([
 (f"For the inflammatory module, Sobol decomposition attributes almost all "
  f"variance in NF-κB suppression to a single parameter ({st_['parameter']}, "
  f"total-order index {f(st_['ST'],2)}; Figure 4d). The prior-predictive "
  f"suppression is {pct(ppv['median'],0)} "
  f"({pct(ppv['lo95'],0)}–{pct(ppv['hi95'],0)}), which brackets the roughly "
  "70% suppression reported experimentally — but this is a prior-predictive "
  "interval, not a fit, and we do not claim it as validation.", "")])

FIG("figures/figure4_kinetics.png", "Figure 4.",
    "Host-interaction kinetics. (a) Posterior-predictive toxin A clearance. "
    "(b) Posterior quantities against the published anchors used to calibrate "
    "them. (c) Marginal posteriors for the Michaelis–Menten parameters. "
    "(d) Sobol sensitivity of NF-κB suppression.")

# ---- Layer 5 (written only if the results exist)
if "l5_cv" in N:
    H("3.10 The surrogate earns its place, narrowly", 2)
    cvrows = sorted(N["l5_cv"].items(), key=lambda kv: -kv[1]["r2"])
    best, second = cvrows[0], cvrows[1]
    sp = N.get("l5_speed", {})
    RICH([
     (f"On {i(N['l5_n_training'])} Latin hypercube samples with identical "
      f"five-fold splits, the best model is {best[0].replace('_', ' ')} "
      f"(R² = {f(best[1]['r2'],4)} ± {f(best[1]['r2_sd'],4)}), followed by "
      f"{second[0].replace('_', ' ')} (R² = {f(second[1]['r2'],4)}). The "
      "margin over the cheap baselines is real but modest, which is worth "
      "saying plainly: on a four-input smooth response surface a tree ensemble "
      "is a strong competitor, and the case for a neural surrogate rests on "
      "inference speed rather than accuracy.", "")])
    if sp:
        RICH([
         (f"That case is quantitative. A surrogate prediction takes "
          f"{f(sp['surrogate_us'],1)} µs against {f(sp['lp_ms'],0)} ms for the "
          f"linear program, a measured speed-up of {i(sp['speedup'])}×, and "
          f"{f(sp['rf_us'],0)} µs for the random forest — so the network is "
          f"{f(sp['rf_us']/sp['surrogate_us'],0)}× faster than the model that "
          "beats it on accuracy. That is the trade-off, stated plainly: the "
          "tree ensemble for offline accuracy, the network for the interactive "
          "interface of Section 6. Ensemble 95% intervals cover "
          f"{pct(sp.get('coverage', float('nan')),1)} of held-out observations.", "")])
    FIG("figures/figure5_surrogate.png", "Figure 5.",
        "Surrogate model. (a) Out-of-fold predictions against flux balance "
        "analysis. (b) Cross-validated accuracy of the surrogate and the "
        "baselines on identical folds. (c) Ensemble predictive intervals and "
        "their empirical coverage.")

H("3.11 Exclusion of C. difficile requires continuous dosing", 2)
ep = N.get("l6_endpoint", {})
RICH([
 ("The competition model reproduces a fact that a single-inoculum model "
  "cannot: ", ""), ("S. boulardii", "i"),
 (" does not colonise. Given once, it washes out and ", ""),
 ("C. difficile", "i"),
 (" recovers; given continuously, it excludes the pathogen and abolishes the "
  f"toxin burden (Figure 6a,b; {f(N.get('l6_toxin_reduction_pct', float('nan')),1)}% "
  "reduction at the endpoint). Over the "
  f"{N['l6_grid_n']}-point parameter grid the outcome is exclusion in "
  f"{N['l6_outcomes'].get('C_difficile_excluded', 0)} cases and coexistence "
  f"in {N['l6_outcomes'].get('coexistence', 0)} (Figure 6c).", "")])
md = N.get("l6_min_dose", {})
RICH([
 ("The clinically actionable output is the minimum dose (Figure 6d). At "
  "physiological transit rates the model requires "
  f"{N['l6_min_dose_overall']} g of dry biomass per day, well inside the "
  "0.25–1 g per day of commercial preparations. The requirement rises at both "
  "extremes of transit — at slow transit because the pathogen is not washed "
  "out and the delivered flux is lower, at fast transit because the yeast "
  "itself is cleared. The prediction that dose requirement is non-monotonic "
  "in transit rate is, to our knowledge, novel and testable in a chemostat.", "")])

FIG("figures/figure6_competition.png", "Figure 6.",
    "Competition and colonisation resistance. (a) Biomass trajectories under "
    "continuous dosing, a single inoculum, and no yeast. (b) Toxin A burden. "
    "(c) Outcome across inhibition strength and transit rate. (d) Minimum "
    "daily dose required for exclusion as a function of transit rate.")

# =================================================================== PREDICTIONS
H("5. Falsifiable predictions", 1)
P("Each prediction below is generated by the model and stated with the "
  "experiment that would refute it.")
import pandas as _pd
pred = _pd.DataFrame([
    dict(Prediction="CNCM I-745 cannot grow on trehalose as sole carbon source, "
                    "while S. cerevisiae S288C can",
         Basis=f"MAL11/AGT1 absent in all {N['l1_n_boulardii_qualifying']} assemblies; "
               f"model growth {f(N['l2_phenotype']['trehalose']['strain'],3)} vs "
               f"{f(N['l2_phenotype']['trehalose']['base'],3)} h⁻¹",
         Refuted_by="Growth on 2% trehalose minimal medium"),
    dict(Prediction="The galactose-negative phenotype is regulatory or allelic, "
                    "not a gene deletion",
         Basis="All seven GAL genes intact in every assembly",
         Refuted_by="Sequencing a GAL structural gene deletion, or restoring "
                    "growth by GAL4 overexpression"),
    dict(Prediction="Galactose growth is more sensitive to transporter titration "
                    "than glucose growth",
         Basis=f"Capacity sweep: {f(N['l2_capacity']['galactose']['deficit_at_1_pct'],0)}% "
               f"deficit on galactose vs {f(N['l2_capacity']['glucose']['deficit_at_1_pct'],0)}% "
               "on glucose at 1 mmol gDW⁻¹ h⁻¹ per permease",
         Refuted_by="Comparative uptake kinetics at limiting sugar"),
    dict(Prediction=f"Gastric survival requires membrane proton leak below "
                    f"{N['l3_kleak_lethal_at_pH2']} L gDW⁻¹ h⁻¹",
         Basis=f"Pump cost {f(N['l3_pump_cost_pH2'],0)} kJ mol⁻¹ H⁺ at pH 2 "
               "exceeds attainable ATP supply above that leak",
         Refuted_by="Proton-flux measurement in acid-adapted cells"),
    dict(Prediction=f"Toxin A half-life under protease exposure is "
                    f"{f(po['half_life_h']['median'],2)} h "
                    f"({f(po['half_life_h']['lo95'],2)}–{f(po['half_life_h']['hi95'],2)})",
         Basis="MCMC posterior calibrated to two published anchors",
         Refuted_by="Time-resolved toxin A degradation assay"),
    dict(Prediction="Dose required to exclude C. difficile is non-monotonic in "
                    "intestinal transit rate",
         Basis=f"Minimum dose {N['l6_min_dose_overall']} g day⁻¹ at intermediate "
               "transit, higher at both extremes",
         Refuted_by="Chemostat co-culture at controlled dilution rates"),
])
TABLE(pred, "Table 1.", "Model predictions and the experiments that would "
      "falsify them.", widths=[2.4, 2.2, 1.8])

# ================================================================ INTEGRATION
FIG("figures/figure7_integration.png", "Figure 7.",
    "Cross-layer architecture with the measured quantities that pass between "
    "layers. Every value shown is read from the machine-generated number "
    "registry, not transcribed.", width=5.6)

# ================================================================== INTERFACE
H("6. Interface", 1)
RICH([
 ("The model is served as a REST API with an accompanying browser dashboard. "
  "Endpoints expose the genome calls, live flux balance analysis under "
  "user-specified exchange bounds, the zone models, the pH response, the "
  "kinetic posterior, the surrogate, and the competition model. The surrogate "
  "is loaded once at start-up, which is what allows the nutrient sliders to "
  "update predictions continuously; the same conditions can be sent to the "
  "linear program for comparison, so the speed–accuracy trade-off is visible "
  "rather than hidden. A plain-language query endpoint is provided and is "
  "described accurately in its own response as deterministic keyword routing, "
  "not a language model.", "")])

# ================================================================ CORRECTIONS
H("7. Corrections to earlier versions of this work", 1)
P("This section is included so that the revision is auditable by anyone "
  "comparing versions.")
corr = _pd.DataFrame([
    dict(Claim="Genome table attributed to CNCM I-745",
         Status="Corrected",
         Detail=f"The values are those of the S288C reference "
                f"({i(N['l1_s288c_seqs'])} sequences, {i(N['l1_s288c_bp'])} bp, "
                f"N50 {i(N['l1_s288c_n50'])}); real S. boulardii assemblies are "
                f"{i(N['l1_sb_bp_min'])}–{i(N['l1_sb_bp_max'])} bp"),
    dict(Claim="HXT9 and HXT11 absent from the assembly",
         Status="Re-derived",
         Detail="True of S. boulardii, but not demonstrable from the genome "
                "previously used, which contains both; now established by "
                "alignment across six assemblies"),
    dict(Claim="Losses span MAL11–MAL33 and IMA1–IMA3",
         Status="Corrected",
         Detail="MAL11 and MAL13 are lost; MAL31, MAL32 and MAL33 are intact. "
                "The isomaltase losses are IMA2, IMA3 and IMA4"),
    dict(Claim="Toxin A cleaved by CAMP factor",
         Status="Corrected",
         Detail="The activity is a 54 kDa serine protease; CAMP factor is "
                "unrelated to this organism"),
    dict(Claim="Buts et al. 2006 cited for toxin A degradation",
         Status="Corrected",
         Detail="That work describes an alkaline phosphatase acting on "
                "lipopolysaccharide, modelled here as a separate activity"),
    dict(Claim="Maltose growth as the strain-specific validation",
         Status="Withdrawn",
         Detail="Does not survive the corrected gene list: the MAL3 locus "
                "supports maltose growth in both models. Trehalose replaces it "
                "as the differential phenotype"),
    dict(Claim="Strain correction yields a functionally distinct model",
         Status="Withdrawn",
         Detail=f"Essentiality is unchanged in {N['l2_ess_n_changed']} genes and "
                f"growth differs on {N['l2_n_differing']} of "
                f"{N['l2_n_substrates']} substrates"),
    dict(Claim="1-D CNN surrogate",
         Status="Replaced",
         Detail="Convolution assumes an input ordering that does not exist for "
                "four unordered nutrient bounds; replaced by a multilayer "
                "perceptron ensemble with checked interval coverage"),
    dict(Claim="Software versions cited",
         Status="Corrected",
         Detail="Several cited versions do not exist; all versions are now "
                "recorded in the environment specification shipped with the code"),
])
TABLE(corr, "Table 2.", "Claims in earlier versions that changed, and why.",
      widths=[1.9, 0.9, 3.6])

# ================================================================= LIMITATIONS
H("8. Limitations", 1)
RICH([
 ("No CNCM I-745 transcriptome from the gastrointestinal tract is publicly "
  "available. The zone layer therefore uses ", ""), ("S. cerevisiae", "i"),
 (" stress-response expression as a proxy, matched condition by condition to "
  "the physicochemical character of each zone. This is a structural "
  "limitation of the available data, not a modelling choice, and it bounds "
  "how literally the zone fluxes should be read.", "")])
P("The phenotype panel is small and literature-derived rather than measured "
  "here; we chose a short fully-sourced panel over a longer one padded with "
  "unsupported entries. The competition model is a two-species abstraction of "
  "a community, and its inhibition term aggregates several documented "
  "mechanisms into one parameter. The inflammatory module is not calibrated. "
  "Assumption diagnostics for the flux contrasts were not assessed.")

# ============================================================== AVAILABILITY
H("9. Data and code availability", 1)
RICH([
 (f"All inputs are recorded in a provenance ledger with SHA-256 digests "
  f"({N['provenance_entries']} entries). The analysis package, layer drivers, "
  "figure builders, API, dashboard and environment specification are provided "
  "with the manuscript, along with the corrected model in SBML. Every number "
  "in this document is regenerated from the result files by the build script; "
  f"{N['n_references_resolved']} of {N['n_references']} references were "
  "verified against CrossRef at build time.", "")])

# ================================================================ REFERENCES
H("References", 1)
seen = set()
for _, r in RA.sort_values("first_author").iterrows():
    if r.key in seen:
        continue
    seen.add(r.key)
    if str(r.resolved) == "yes":
        yr = int(float(r.year)) if str(r.year) not in ("", "nan") else ""
        vol = "" if str(r.volume) in ("", "nan") else f" {int(float(r.volume))}"
        pg = "" if str(r.page) in ("", "nan") else f": {r.page}"
        txt = (f"{r.first_author} et al. ({yr}) {str(r.title).strip()}. "
               f"{str(r.journal).replace('&amp;', '&')}{vol}{pg}. doi:{r.doi}")
    else:
        txt = f"{str(r.title).strip()}. doi:{r.doi} (preprint server record)"
    p = doc.add_paragraph(txt)
    p.paragraph_format.space_after = Pt(3)
    for run in p.runs:
        run.font.size = Pt(8.5)
